name: ğŸ§ª train-a CI

on:
  pull_request:
    paths:
      - 'train-a/**'

jobs:
  ci:
    name: ğŸ§ª CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'train-a'

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ’© Enable Corepack before setting up Node
        run: corepack enable

      - name: ğŸ”¨ install node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: 'train-a/package.json'
          cache-dependency-path: '**/train-a/package-lock.json'

      - name: ğŸ”¨ install package
        run: npm install

      - name: ğŸ‘ Typescript checks
        run: npx tsc

      - name: ğŸ” ES lint
        run: npm run lint

      - name: ğŸ” Stylelint
        run: npm run stylelint

      - name: ğŸ§ª Tests
        run: npm run test:staged